# 10-minutely backup job
name: "backup db"
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  backup-job:
    runs-on: ubuntu-latest
    steps:
    - name: ping
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ secrets.BACKUP_URL }}
        method: 'GET'
        customHeaders: '{
              "Authorization":  "${{ secrets.TOKEN }}"
            }'
        ignoreStatusCodes: 'false'
        timeout: 10000
    - name: done
      run:  echo Daily backup started!
