# close issue given issue id

name: close-issue

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to close'
        required: true
jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{github.event.inputs.issue_number}}
          comment: Job successfully synced, closing issue ${{github.event.issue.number}}.